In [174]:
import pandas as pd

In [175]:
import os
os.getcwd()

'c:\\Users\\Usuario\\Desktop\\the bridge\\github\\2603_ds_sql_thebridge\\Practica\\3-Proyecto'

### 1. LOAD
   - Concatenated 4 class CSVs into df_students
   - Loaded claustro.csv into df_faculty

In [176]:
# we load all of the class CSVs and stack them into just one dataframe

df_students = pd.concat([
    pd.read_csv("data/clase_1.csv", sep = ";"),
    pd.read_csv("data/clase_2.csv", sep = ";"),
    pd.read_csv("data/clase_3.csv", sep = ";"),
    pd.read_csv("data/clase_4.csv", sep = ";")

], ignore_index=True)

In [177]:
# load faculty CSV separately (different structure)

df_faculty = pd.read_csv("data/claustro.csv", sep=";")

### 2. CLEAN
   - Fixed typo (FullSatck → FullStack)
   - Melted project columns from wide → long format (df_melted)
   - Dropped NaN rows (260 real grades remaining)

In [178]:
# 9 columns were expected but we got 15 instead 

print(df_students.shape)
print(df_faculty.shape)

(52, 15)
(10, 6)

In [179]:
# the 15 columns are due to the 10 projects that there are (5 for DS and 5 for FS)

print(df_students.columns.tolist())

['Nombre', 'Email', 'Promoción', 'Fecha_comienzo', 'Campus', 'Proyecto_HLF', 'Proyecto_EDA', 'Proyecto_BBDD', 'Proyecto_ML', 'Proyecto_Deployment', 'Proyecto_WebDev', 'Proyecto_FrontEnd', 'Proyecto_Backend', 'Proyecto_React', 'Proyecto_FullSatck']

In [180]:
# 1st we see what the data looks like

df_students.head(2)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto,NaN,NaN,NaN,NaN,NaN
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto,NaN,NaN,NaN,NaN,NaN

In [181]:
# we correct the typo on the column named "Proyecto_FullSatck"

df_students = df_students.rename(columns = {"Proyecto_FullSatck": "Proyecto_FullStack"})

In [182]:
# 2nd we see how many null values in each column of our dataframe

print(df_students.isnull().sum())

Nombre                  0
Email                   0
Promoción               0
Fecha_comienzo          0
Campus                  0
Proyecto_HLF           27
Proyecto_EDA           27
Proyecto_BBDD          27
Proyecto_ML            27
Proyecto_Deployment    27
Proyecto_WebDev        25
Proyecto_FrontEnd      25
Proyecto_Backend       25
Proyecto_React         25
Proyecto_FullStack     25
dtype: int64

In [183]:
# we create a list of the columns that we want to convert into rows 

project_columns = [
    "Proyecto_HLF", "Proyecto_EDA", "Proyecto_BBDD", "Proyecto_ML", 
    "Proyecto_Deployment", "Proyecto_WebDev", "Proyecto_FrontEnd", 
    "Proyecto_Backend", "Proyecto_React", "Proyecto_FullStack"
]

In [ ]:
df_melted = df_students.melt( # df_students.melt() — we're calling the melt function -> transforms the datafarme from wide to long format
    id_vars = ["Nombre", "Email", "Promoción", "Fecha_comienzo", "Campus"], # id_vars = [...] -> these are the columns we want to keep as-is
    value_vars = project_columns, # value_vars = project_columns -> these are the columns we wanto to convert into rows // instead of 10 project columns, each project becomes its own row
    var_name = "tipo_proyecto", # var_name = "tipo_proyecto" -> this is the name we give to the new column that stores the project column names (i.e, "Projecto_EDA")
    value_name = "resultado" # value_name = "resultado" -> this is the name we give to the new column that stores the values (Apto // No Apto)
)

In [185]:
df_melted.head(5)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,tipo_proyecto,resultado
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto

In [186]:
# we need to drop the NULL values since they don't represent real grades 

df_melted = df_melted.dropna(subset = ["resultado"])
print(df_melted.shape)

(260, 7)

In [187]:
df_melted

,Nombre,Email,Promoción,Fecha_comienzo,Campus,tipo_proyecto,resultado
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto
...,...,...,...,...,...,...,...
515,Rita Olivares,Rita_Olivares@gmail.com,Febrero,12/02/2024,Valencia,Proyecto_FullStack,Apto
516,Cleto Montes,Cleto_Montes@gmail.com,Febrero,12/02/2024,Valencia,Proyecto_FullStack,Apto
517,Marino Castilla,Marino_Castilla@gmail.com,Febrero,12/02/2024,Valencia,Proyecto_FullStack,No Apto
518,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,Febrero,12/02/2024,Valencia,Proyecto_FullStack,Apto
519,Noemí Vilanova,Noemí_Vilanova@gmail.com,Febrero,12/02/2024,Valencia,Proyecto_FullStack,Apto

### 3. LOOKUP TABLES
   - df_campus         (Madrid, Valencia...)
   - df_tipo_proyecto  (HLF, EDA, BBDD...)
   - df_promocion      (Septiembre, Febrero)
   - df_modalidad      (Presencial, Online)
   - df_vertical       (DS, FS)
   - df_rol            (Teacher, Teacher Assistant)

In [188]:
# in our df_melted each campus is repeated multiple times
# we create a new dataframe (campus) and with "drop_duplicates" we keep only 1 campus
# we use reset_index because, for example, if "Valencia" was originally on row 515, it's index would still be 515
# drop = True: with this we're telling the system "don't keep the old index, throw it away"
# index + 1 because Postgre SQL expects IDs to start at 1

df_campus = df_melted[["Campus"]].drop_duplicates().reset_index(drop = True)
df_campus["id"] = df_campus.index + 1
print(df_campus)

     Campus  id
0    Madrid   1
1  Valencia   2

In [189]:
# same thing as before
# we assign each project and ID to only have one of each

df_tipo_proyecto = df_melted[["tipo_proyecto"]].drop_duplicates().reset_index(drop = True)
df_tipo_proyecto["id"] = df_tipo_proyecto.index + 1
df_tipo_proyecto = df_tipo_proyecto.rename(columns =  {"id": "tipo_proyecto_id"})
print(df_tipo_proyecto)

         tipo_proyecto  tipo_proyecto_id
0         Proyecto_HLF                 1
1         Proyecto_EDA                 2
2        Proyecto_BBDD                 3
3          Proyecto_ML                 4
4  Proyecto_Deployment                 5
5      Proyecto_WebDev                 6
6    Proyecto_FrontEnd                 7
7     Proyecto_Backend                 8
8       Proyecto_React                 9
9   Proyecto_FullStack                10

In [190]:
# same thing as before
# we assign each promotion and ID to only have one of each

df_promocion = df_melted[["Promoción"]].drop_duplicates().reset_index(drop = True)
df_promocion["id"] = df_promocion.index + 1
print(df_promocion)

    Promoción  id
0  Septiembre   1
1     Febrero   2

In [191]:
# same thing as before
# we assign each modalidad (presencial or online) and ID to only have one of each

df_modalidad = df_faculty[["Modalidad"]].drop_duplicates().reset_index(drop = True)
df_modalidad["id"] = df_modalidad.index + 1
print(df_modalidad)

    Modalidad  id
0  Presencial   1
1      Online   2

In [192]:
# same thing as before
# we assign each vertical (DS or FS) and ID to only have one of each

df_vertical = df_faculty[["Vertical"]].drop_duplicates().reset_index(drop = True)
df_vertical["id"] = df_vertical.index + 1
print(df_vertical)

  Vertical  id
0       DS   1
1       FS   2

In [193]:
# same thing as before
# we assign each role (teacher or TA) and ID to only have one of each

df_rol = df_faculty[["Rol"]].drop_duplicates().reset_index(drop = True)
df_rol["id"] = df_rol.index + 1
print(df_rol)

  Rol  id
0  TA   1
1  LI   2

### DATAFRAMES CREADOS

✅ df_campus

✅ df_tipo_proyecto

✅ df_promocion

✅ df_modalidad

✅ df_vertical

✅ df_rol

### 4. Add id to df_students
   - df_students → add estudiante_id to the dataframe

In [194]:
df_students["id"] = df_students.index + 1
df_students = df_students.rename(columns =  {"id": "estudiante_id"})
print(df_students[["estudiante_id", "Nombre"]].head())

   estudiante_id            Nombre
0              1      Jafet Casals
1              2  Jorge Manzanares
2              3     Onofre Adadia
3              4      Merche Prada
4              5      Pilar Abella

### 5. MAIN TABLES
   - df_students → merged with campus + promocion → kept Nombre, Email, campus_id, promocion_id
   - df_faculty  → merged with rol + campus + vertical → kept Nombre, rol_id, campus_id, vertical_id

In [195]:
# we now need to create the main entity tables (studnets and faculty)
# let's start with estudiante
# how = left -> we want to keep all of the columns from df_students and match campus where possible

df_students = df_students.merge(df_campus, on = "Campus", how = "left")
print(df_students[["Nombre", "Campus", "id"]].head())

             Nombre  Campus  id
0      Jafet Casals  Madrid   1
1  Jorge Manzanares  Madrid   1
2     Onofre Adadia  Madrid   1
3      Merche Prada  Madrid   1
4      Pilar Abella  Madrid   1

In [196]:
print(df_students.columns.tolist())
print(df_campus.columns.tolist())

['Nombre', 'Email', 'Promoción', 'Fecha_comienzo', 'Campus', 'Proyecto_HLF', 'Proyecto_EDA', 'Proyecto_BBDD', 'Proyecto_ML', 'Proyecto_Deployment', 'Proyecto_WebDev', 'Proyecto_FrontEnd', 'Proyecto_Backend', 'Proyecto_React', 'Proyecto_FullStack', 'estudiante_id', 'id']
['Campus', 'id']

In [197]:
# id is too generic // we'll change it to campus_id

df_students = df_students.rename(columns =  {"id": "campus_id"})

In [198]:
# same as before but instead of campus we now merge with promocion

df_students = df_students.merge(df_promocion, on = "Promoción", how = "left")
print(df_students[["Nombre", "Promoción", "id"]].head())

             Nombre   Promoción  id
0      Jafet Casals  Septiembre   1
1  Jorge Manzanares  Septiembre   1
2     Onofre Adadia  Septiembre   1
3      Merche Prada  Septiembre   1
4      Pilar Abella  Septiembre   1

In [199]:
# id is too generic // we'll change it to promocio_id

df_students = df_students.rename(columns =  {"id": "promocion_id"})

In [200]:
df_faculty.head(1)

      Nombre Rol Vertical   Promocion  Campus   Modalidad
0  Noa Yáñez  TA       DS  Septiembre  Madrid  Presencial

In [201]:
print(df_faculty.columns.tolist())

['Nombre', 'Rol', 'Vertical', 'Promocion', 'Campus', 'Modalidad']

In [202]:
# same as we did before with students
# but now we merge df_faculty with df_rol, df_campus and df_vertical
# since "id" is too generic for each merger // we modify each "id" depending on their "parent" df

df_faculty = df_faculty.merge(df_rol, on = "Rol", how = "left")
df_faculty = df_faculty.rename(columns = {"id": "rol_id"})

df_faculty = df_faculty.merge(df_campus, on = "Campus", how = "left")
df_faculty = df_faculty.rename(columns = {"id": "campus_id"})

df_faculty = df_faculty.merge(df_vertical, on = "Vertical", how = "left")
df_faculty = df_faculty.rename(columns = {"id": "vertical_id"})

df_faculty = df_faculty[["Nombre", "rol_id", "campus_id", "vertical_id"]]
print(df_faculty.head())

              Nombre  rol_id  campus_id  vertical_id
0          Noa Yáñez       1          1            1
1  Saturnina Benitez       1          1            1
2         Anna Feliu       1          1            2
3      Rosalva Ayuso       1          2            2
4   Ana Sofía Ferrer       1          2            2

### 5. NEXT UP
   - Build df_calificacion from df_melted
   - Connect to PostgreSQL and insert everything

In [203]:
# our df_melted currently looks like this 
# we need to replace the text values with their IDs so that PostgreSQL may read it correctly

df_melted.head(1)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,tipo_proyecto,resultado
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Proyecto_HLF,Apto

In [204]:
# here we merge df_melted and df_students to get "estudiante_id"
# we only merge on "Nombre" (to match on) and "estudiante_id" to keep
# everything else is uncessary

df_calificacion = df_melted.merge(df_students[["Nombre", "estudiante_id"]], on = "Nombre", how = "left")

In [205]:
# same as before but in this case we merge df_califacion and df_tipo_proyecto to get ·proyecto_id"

df_calificacion = df_calificacion.merge(df_tipo_proyecto, on = "tipo_proyecto", how = "left")

In [206]:
# lastly we modify our df_califacion to only keep what we need

df_calificacion = df_calificacion[["estudiante_id", "tipo_proyecto_id", "resultado"]]

In [ ]:
# double check to see if our df is consisted of pure IDs except the "resultado" column

print(df_calificacion.head(10))

   estudiante_id  tipo_proyecto_id resultado
0              1                 1      Apto
1              2                 1      Apto
2              3                 1      Apto
3              4                 1      Apto
4              5                 1      Apto
5              6                 1      Apto
6              7                 1   No Apto
7              8                 1   No Apto
8              9                 1      Apto
9             10                 1      Apto

In [ ]:
# one last check to make sure that we no longer have null values 

print(df_calificacion.shape)
print(df_calificacion.isnull().sum())

(260, 3)
estudiante_id       0
tipo_proyecto_id    0
resultado           0
dtype: int64

### RECAP

✅ df_campus          (2 rows)

✅ df_vertical        (2 rows)

✅ df_modalidad       (2 rows)

✅ df_promocion       (2 rows)

✅ df_rol             (2 rows)

✅ df_tipo_proyecto   (10 rows)

✅ df_students        (52 rows)

✅ df_faculty         (10 rows)

✅ df_calificacion    (260 rows)